/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation
         * @description The invited person chooses a name and a password and gets an account in the institution
         *     that invited them, verified, with the invited role, and is signed in (the session id is
         *     regenerated). An unknown, used or cancelled token is 404; an expired one is 410; the order
         *     of the checks is in the endpoint file. Public. Limited to 10 requests per hour per IP address.
         */
        post: operations["auth.acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start the session and set the CSRF cookie
         * @description Starts the browser's session if it has none and sets the `XSRF-TOKEN` cookie. The web
         *     application calls it once before its first state-changing request, then copies the
         *     cookie's value into the `X-XSRF-TOKEN` header of every request that changes something.
         *     Public. Limited to 60 requests per minute per IP address.
         */
        get: operations["auth.csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password reset link
         * @description Sends a reset link to the address, if it belongs to an account. The answer is the same
         *     either way, so the endpoint does not tell whether an account exists. Public. Limited
         *     to 5 requests per hour per IP address, and 3 per hour per email address.
         */
        post: operations["auth.forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State of the API and of the services it depends on
         * @description Says whether the database and Redis answer, and returns the database server's clock.
         *     Public. Limited to 60 requests per minute per IP address.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/institution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The institution's profile
         * @description The profile of the signed-in user's own institution; there is no way to name another. An
         *     owner or a manager may read it. A platform admin has no institution: 403. Signed-in user.
         */
        get: operations["institution.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the institution's profile
         * @description Every field is optional; only those sent change. Strings are trimmed, and an optional field
         *     sent empty is cleared. The suspension and the logo cannot be reached from here. Owner only.
         */
        patch: operations["institution.update"];
        trace?: never;
    };
    "/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The invitations that have not been accepted
         * @description Live and expired ones, newest first. The token is never returned. Owner only.
         */
        get: operations["invitation.index"];
        put?: never;
        /**
         * Invite a person
         * @description Invites an address to join the institution as owner or manager, and sends the email in the
         *     institution's language. A live invitation for the same address is replaced: its link stops
         *     working. Owner only. Limited to 20 requests per hour per user.
         */
        post: operations["invitation.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/{invitation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel an invitation
         * @description Its link stops working; the row is deleted. An invitation that is unknown, already
         *     accepted, already cancelled or another institution's answers 404. Owner only.
         */
        delete: operations["invitation.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Signs a user in with email and password. The session id is regenerated. A platform
         *     admin signs in here too. A user with two-factor authentication is not signed in yet: the
         *     answer is `{"data":{"two_factor_required":true}}` and the sign-in is finished by
         *     `POST /auth/two-factor-challenge`. Public. Limited to 10 requests per minute per IP address, and
         *     5 failed attempts per minute for one email address from one IP address.
         */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/institution/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the institution's logo
         * @description Send one `file` part (`multipart/form-data`): a JPEG, PNG or WebP of at most 5 MB, 8 000
         *     pixels on a side and 40 million pixels. It is recognised by its content, re-encoded into
         *     three WebP sizes (64, 160, 480 pixels), stripped of every piece of metadata, and the
         *     upload itself is never kept. The previous logo's files are deleted once the new one is
         *     stored. Owner only. Limited to 10 requests per hour per user.
         */
        put: operations["logo.update"];
        post?: never;
        /**
         * Remove the institution's logo
         * @description The institution is shown with its initials again. Answers 204 whether or not there was a
         *     logo. Owner only.
         */
        delete: operations["logo.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Ends the session: it is destroyed in Redis and the CSRF token regenerated, so the old
         *     session cookie opens nothing. Signed-in user.
         */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description The user and their institution (`null` for a platform admin). The web application reads
         *     it on every page of the admin area. A user whose institution was suspended since
         *     sign-in is refused, and the session is ended. Signed-in user.
         */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the signed-in user's settings
         * @description In this slice, the language of the admin area (`fr` or `en`). It also becomes the language of
         *     the emails sent to this user from then on. Only the signed-in user's own row changes; any
         *     other field of the body is ignored. Signed-in user.
         */
        patch: operations["me.update"];
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an institution and its owner
         * @description Creates the institution and its first user, the owner, in one step, queues the
         *     verification email and signs the owner in. Public. Limited to 10 requests per hour
         *     per IP address.
         */
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the verification email again
         * @description Sends a new verification email to the signed-in user; the previous link stops working.
         *     Signed-in user. Limited to 3 requests per minute per user.
         */
        post: operations["auth.resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password
         * @description Sets a new password with the token of the reset link. The user is not signed in, and
         *     their other sessions stop working. Public. Limited to 10 requests per hour per IP address.
         */
        post: operations["auth.resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/two-factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The state of the signed-in user's two-factor authentication
         * @description `enabled`: confirmed and asked at sign-in. `setup_started`: a secret was issued and not
         *     confirmed. `recovery_codes_left`: how many unused recovery codes remain, `null` when not
         *     enabled. Neither the secret nor a code is returned. Signed-in user.
         */
        get: operations["twoFactor.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/two-factor/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start turning two-factor on
         * @description Issues a new secret (a setup not yet confirmed is replaced) after the password is checked.
         *     Not active until confirmed. The answer holds the secret and the `otpauth` link; the web
         *     page draws the QR code in the browser. Signed-in user. Limited to 10 requests per minute
         *     per user, shared with confirm, disable and recovery codes.
         */
        post: operations["twoFactor.setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/two-factor/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn two-factor on
         * @description Confirms the setup with a first code from the authenticator application (6 digits; the
         *     previous and the next period are accepted; a period already used is not) and returns
         *     the eight recovery codes, shown only here and in the renewal. Open sessions stay open. A
         *     wrong code does not end the setup. Signed-in user. Limited to 10 requests per minute per
         *     user, shared with setup, disable and recovery codes.
         */
        post: operations["twoFactor.confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/two-factor/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn two-factor off
         * @description Clears the secret, the recovery codes, the confirmation time and the stored period after
         *     the password is checked. A setup that was never confirmed counts as not turned on.
         *     Signed-in user. Limited to 10 requests per minute per user, shared with setup, confirm and
         *     recovery codes.
         */
        post: operations["twoFactor.disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/two-factor/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew the recovery codes
         * @description Replaces the recovery codes with eight new ones after the password is checked; the old
         *     ones stop working. Shown only here. Signed-in user. Limited to 10 requests per minute per
         *     user, shared with setup, confirm and disable.
         */
        post: operations["twoFactor.recoveryCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/two-factor-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish signing in with a code
         * @description The second step of signing in for a person who has two-factor authentication turned on:
         *     one `code` from the authenticator application (6 digits; the previous and the next
         *     30-second period are accepted, a period already used is not) or one `recovery_code`
         *     (checked first when both are sent; used up by a success). It only ever finishes the
         *     sign-in that the password step recorded in this browser's session, for five minutes;
         *     five wrong codes end it. Five wrong codes in 15 minutes for one account, from any browser or
         *     address, answer 429 even for a right code. The session id is regenerated. Public. Limited to 10 requests
         *     per minute per IP address.
         */
        post: operations["auth.twoFactorChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The users of the institution
         * @description Owners first, then managers, each by name (case and accents ignored), then by email. A
         *     removed user is not listed. Owner only.
         */
        get: operations["user.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a user
         * @description The user can no longer sign in and their next request is refused. Their address is freed;
         *     their name is kept for the audit log. An institution keeps at least one owner. Removing
         *     oneself also ends one's own session. Owner only.
         */
        delete: operations["user.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user}/two-factor/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn off another user's two-factor authentication
         * @description For a person who has lost both their device and their recovery codes: the secret, the
         *     recovery codes, the confirmation time and the stored period are cleared; their open
         *     sessions stay open and their next sign-in asks for the password only. The owner's own
         *     password is asked: a wrong one is a 422, and the fifth in 15 minutes ends the owner's
         *     session (401). Not for oneself (the page "Mon compte" asks for the password). Owner only.
         *     Limited to 10 requests per minute per user, shared with the own-settings routes.
         */
        post: operations["user.resetTwoFactor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an email address
         * @description Verifies the address with the token of the link sent by email. The person may open the
         *     link in another browser than the one they registered with, so no session is needed and
         *     nobody is signed in by it. Public. Limited to 10 requests per minute per IP address.
         */
        post: operations["auth.verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptInvitationRequest
         * @description docs/api/auth/POST-auth-accept-invitation.md. Only the token is judged here: the rest of
         *     the body is judged after the token has been found (an unknown token answers 404 before any
         *     422, so a bad body never reveals whether a token is valid).
         */
        AcceptInvitationRequest: {
            token: string;
        };
        /**
         * CreateInvitationRequest
         * @description docs/api/users/POST-invitations.md
         */
        CreateInvitationRequest: {
            /**
             * Format: email
             * @description `max` before `email`: an address that is far too long is told "too long".
             */
            email: string;
            role: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** InvitationResource */
        InvitationResource: unknown[];
        /** LoginRequest */
        LoginRequest: {
            email: string;
            password: string;
        };
        /**
         * PasswordRequest
         * @description The password of the signed-in user, asked again to change the second factor.
         */
        PasswordRequest: {
            password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            institution_name: string;
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string|null} */
            language?: "fr" | "en" | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        /**
         * TwoFactorCodeRequest
         * @description The code of the authenticator application that confirms a setup. Only its presence is judged
         *     here: anything that is not exactly 6 digits (a number, a list, a long text) is answered
         *     `code: invalid` by the controller.
         */
        TwoFactorCodeRequest: {
            code: string;
        };
        /**
         * UpdateInstitutionRequest
         * @description docs/api/institution/PATCH-institution.md: every field is optional, only those sent change.
         */
        UpdateInstitutionRequest: {
            name?: string;
            type?: string;
            description?: string | null;
            address?: string | null;
            city?: string | null;
            phone?: string | null;
            /** Format: email */
            contact_email?: string | null;
            timezone?: string;
            language?: string;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** @enum {string} */
            language: "fr" | "en";
        };
        /** UserResource */
        UserResource: unknown[];
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            token: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.acceptInvitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"] & {
                    name?: string;
                    password?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth.forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @constant */
                            status: "ok";
                            checks: {
                                /** @constant */
                                database: "ok";
                                /** @constant */
                                redis: "ok";
                            };
                            time: string;
                        };
                    };
                };
            };
        };
    };
    "institution.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            type: "school" | "university" | "association" | "other";
                            description: string | null;
                            address: string | null;
                            city: string | null;
                            phone: string | null;
                            contact_email: string | null;
                            timezone: string;
                            /** @enum {string} */
                            language: "fr" | "en";
                            logo: {
                                sm: string;
                                md: string;
                                lg: string;
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "institution.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateInstitutionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            type: "school" | "university" | "association" | "other";
                            description: string | null;
                            address: string | null;
                            city: string | null;
                            phone: string | null;
                            contact_email: string | null;
                            timezone: string;
                            /** @enum {string} */
                            language: "fr" | "en";
                            logo: {
                                sm: string;
                                md: string;
                                lg: string;
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "invitation.index": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager";
                            invited_by: string | null;
                            created_at: string;
                            expires_at: string;
                            expired: boolean;
                        }[];
                        meta: {
                            page: number;
                            per_page: number;
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "invitation.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description `InvitationResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager";
                            invited_by: string | null;
                            created_at: string;
                            expires_at: string;
                            expired: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "invitation.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The invitation UUID */
                invitation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        } | {
                            two_factor_required: boolean;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "logo.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            type: "school" | "university" | "association" | "other";
                            description: string | null;
                            address: string | null;
                            city: string | null;
                            phone: string | null;
                            contact_email: string | null;
                            timezone: string;
                            /** @enum {string} */
                            language: "fr" | "en";
                            logo: {
                                sm: string;
                                md: string;
                                lg: string;
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "logo.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "me.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.resendVerification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "twoFactor.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            enabled: boolean;
                            setup_started: boolean;
                            recovery_codes_left: number | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "twoFactor.setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            secret: string;
                            otpauth_url: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "twoFactor.confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorCodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            recovery_codes: string[];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "twoFactor.disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "twoFactor.recoveryCodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            recovery_codes: string[];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.twoFactorChallenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    code?: string;
                    recovery_code?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
        };
    };
    "user.index": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager";
                            email_verified: boolean;
                            last_login_at: string | null;
                            two_factor_enabled: boolean;
                            is_you: boolean;
                        }[];
                        meta: {
                            page: number;
                            per_page: number;
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "user.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user UUID */
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "user.resetTwoFactor": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user UUID */
                user: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description An error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.verifyEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
