/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start the session and set the CSRF cookie
         * @description Starts the browser's session if it has none and sets the `XSRF-TOKEN` cookie. The web
         *     application calls it once before its first state-changing request, then copies the
         *     cookie's value into the `X-XSRF-TOKEN` header of every request that changes something.
         *     Public. Limited to 60 requests per minute per IP address.
         */
        get: operations["auth.csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password reset link
         * @description Sends a reset link to the address, if it belongs to an account. The answer is the same
         *     either way, so the endpoint does not tell whether an account exists. Public. Limited
         *     to 5 requests per hour per IP address, and 3 per hour per email address.
         */
        post: operations["auth.forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State of the API and of the services it depends on
         * @description Says whether the database and Redis answer, and returns the database server's clock.
         *     Public. Limited to 60 requests per minute per IP address.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Signs a user in with email and password. The session id is regenerated. A platform
         *     admin signs in here too. Public. Limited to 10 requests per minute per IP address, and
         *     5 failed attempts per minute for one email address from one IP address.
         */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Ends the session: it is destroyed in Redis and the CSRF token regenerated, so the old
         *     session cookie opens nothing. Signed-in user.
         */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description The user and their institution (`null` for a platform admin). The web application reads
         *     it on every page of the admin area. A user whose institution was suspended since
         *     sign-in is refused, and the session is ended. Signed-in user.
         */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an institution and its owner
         * @description Creates the institution and its first user, the owner, in one step, queues the
         *     verification email and signs the owner in. Public. Limited to 10 requests per hour
         *     per IP address.
         */
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the verification email again
         * @description Sends a new verification email to the signed-in user; the previous link stops working.
         *     Signed-in user. Limited to 3 requests per minute per user.
         */
        post: operations["auth.resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password
         * @description Sets a new password with the token of the reset link. The user is not signed in, and
         *     their other sessions stop working. Public. Limited to 10 requests per hour per IP address.
         */
        post: operations["auth.resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an email address
         * @description Verifies the address with the token of the link sent by email. The person may open the
         *     link in another browser than the one they registered with, so no session is needed and
         *     nobody is signed in by it. Public. Limited to 10 requests per minute per IP address.
         */
        post: operations["auth.verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** LoginRequest */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            institution_name: string;
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string|null} */
            language?: "fr" | "en" | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        /** UserResource */
        UserResource: unknown[];
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            token: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth.forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @constant */
                            status: "ok";
                            checks: {
                                /** @constant */
                                database: "ok";
                                /** @constant */
                                redis: "ok";
                            };
                            time: string;
                        };
                    };
                };
            };
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            /** @enum {string} */
                            role: "owner" | "manager" | "platform_admin";
                            email_verified: boolean;
                            /** @enum {string} */
                            language: "fr" | "en";
                            institution: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                type: "school" | "university" | "association" | "other";
                            } | null;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.resendVerification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.verifyEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
